server:
  port: 8888
spring:
  application:
    name: blogpost
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: SunR!se@2035
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blogpostdb
#    username: root
#    password: root
#  jpa:
#    properties:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create